import Head from "next/head";
import Add from "../src/components/Add";
import Employees from "../src/components/Employees";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl text-center">Welcome to Aroha Employees</h1>
        <Employees />
        <Add />
      </main>
    </div>
  );
}