// import Head from "next/head";
// import Link from "next/link";

import NotesList from "../components/NotesApp/NotesList";
import styles from "../components/NotesApp/Notes.module.css";
import { useState } from "react";
import WeatherApp from "../components/WeatherApp/WeatherApp";
import Counter from "../components/Practice/Counter";
import SearchBar from "../components/CryptoCurrency/SearchBar";
import Coins from "../components/CryptoCurrency/Coins";
import CoinList from "../components/CryptoCurrency/CoinList";
import Layout from "../components/CryptoCurrency/Layout";
import Counter1 from "../components/Practice/Counter1";

// export default function Home() {
//   return (
//     <div>
//       <Head>
//         <title>Home</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main>
//         <h1 className="text-4xl text-center">Welcome to Aroha</h1>
//         <Link href="/employees">Click here</Link> to view all employees
//       </main>
//     </div>
//   );
// }

// const DUMMY_MEETUPS = [
//   {
//     id: "m1",
//     title: "A First Meetup",
//     image:
//       "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Stadtbild_M%C3%BCnchen.jpg/1280px-Stadtbild_M%C3%BCnchen.jpg",
//     address: "Some address 5, 12345 Some City",
//     description: "This is a first meetup!",
//   },
//   {
//     id: "m2",
//     title: "A Second Meetup",
//     image:
//       "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Stadtbild_M%C3%BCnchen.jpg/1280px-Stadtbild_M%C3%BCnchen.jpg",
//     address: "Some address 10, 12345 Some City",
//     description: "This is a second meetup!",
//   },
// ];
// function HomePage({ countries }) {
//   console.log(countries);
//   const [keyword, setKeyword] = useState(" ");

//   const filteredCountries = countries.filter(
//     (country) =>
//       country.name.common.toLowerCase().includes(keyword) ||
//       country.region.toLowerCase().includes(keyword)
//       // country.subregion.toLowerCase().includes(keyword)
//   );

//   const onInputChange = (e) => {
//     e.preventDefault();

//     setKeyword(e.target.value.toLowerCase());
//   };

//   return (
//     <>
//       {/* <MeetupList meetups={props.meetups} /> */}

//       {/* <div className={styles.pagecontainer}>
//      <ToolBar />

//       <div className={styles.main}>
//         <h1>Next.js News App</h1>

//         <h3>Your one stop shop for the latest news articles</h3>
//       </div>
//     </div> */}

//       {/* <Layout>
//         <div className={styles.counts}>Found {countries.length} countries</div>
//         <SearchInput
//           placeholder="Filter by Name,Region or SubRegion"
//           onChange={onInputChange}
//         />
//         <CountriesTable countries={filteredCountries} />
//       </Layout> */}
//     </>
//   );
// }

// export const getStaticProps = async () => {
//   const res = await fetch("https://restcountries.com/v3.1/all");
//   const countries = await res.json();

//   return {
//     props: {
//       countries,
//     },
//   };
// };

// export async function getStaticProps() {
//   //fetch data from an api
//   return {
//     props: {
//       meetups: DUMMY_MEETUPS,
//     },
//     revalidate: 10,
//   };
// }

// export async function getServerSideProps(context){
//   const req=context.req
//   const res=context.res
//   //fetch data from an api
//   return{
//     props:{
//       meetups:DUMMY_MEETUPS
//     }
//   }
// }

// export default HomePage;

function HomePage({ filteredCoins }) {
  // const [search, setSearch] = useState("");
  // const allCoins = filteredCoins.filter((coin) =>
  //   coin.name.toLowerCase().includes(search.toLowerCase())
  // );
  // const handleChange = (e) => {
  //   e.preventDefault();
  //   setSearch(e.target.value.toLowerCase());
  // };
  const [notes, setNotes] = useState([
    {
      id: Math.floor(Math.random() * 10),
      text: "This is my first Note",
      date: "15/06/2022",
    },
    {
      id: Math.floor(Math.random() * 10),
      text: "This is my second Note",
      date: "15/06/2022",
    },
    {
      id: Math.floor(Math.random() * 10),
      text: "This is my third Note",
      date: "15/06/2022",
    },
  ]);
  const addNote = (text) => {
    const date = new Date();
    const newNote = {
      id: Math.floor(Math.random() * 10),
      text: text,
      date: date.toLocaleDateString(),
    };
    const newNotes = [...notes, newNote];
    setNotes(newNotes);
  };
  return (
    // <Layout>
    //   <div className="flex flex-col items-center mt-2">
    //     <SearchBar type="text" placeholder="search" onChange={handleChange} />
    //     <CoinList filteredCoins={allCoins} />
    //   </div>
    // </Layout>

    <div className={styles.contaimer}>
      <NotesList notes={notes} onAddNote={addNote} />
      <Counter1 />
    </div>
  );
}

export default HomePage;

// export const getServerSideProps = async () => {
//   const res = await fetch(
//     "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
//   );
//   const filteredCoins = await res.json();
//   return {
//     props: {
//       filteredCoins,
//     },
//   };
// };
