// import Head from "next/head";
// import Link from "next/link";

// export default function Home() {
//   return (
//     <div>
//       <Head>
//         <title>Home</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main>
//         <h1 className="text-4xl text-center">Welcome to Aroha</h1>
//         <Link href="/employees">Click here</Link> to view all employees
//       </main>
//     </div>
//   );
// }

import MeetupList from "../components/meetups/MeetupList";
import React, { useState } from "react";
import FizzBuzz from "../components/Practice/FizzBuzz";
import SearchText from "../components/Practice/SearchText";
import ShowHide from "../components/Practice/ShowHide";
import styles from "../styles/Home.module.css";
import ToolBar from "../components/NewsApp/ToolBar";
import Layout from "../components/Countries/Layout/Layout";
import SearchInput from "../components/Countries/SearchInput/SearchInput";
import CountriesTable from "../components/Countries/CountriesTable/CountriesTable";
// const DUMMY_MEETUPS = [
//   {
//     id: "m1",
//     title: "A First Meetup",
//     image:
//       "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Stadtbild_M%C3%BCnchen.jpg/1280px-Stadtbild_M%C3%BCnchen.jpg",
//     address: "Some address 5, 12345 Some City",
//     description: "This is a first meetup!",
//   },
//   {
//     id: "m2",
//     title: "A Second Meetup",
//     image:
//       "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Stadtbild_M%C3%BCnchen.jpg/1280px-Stadtbild_M%C3%BCnchen.jpg",
//     address: "Some address 10, 12345 Some City",
//     description: "This is a second meetup!",
//   },
// ];
function HomePage({ countries }) {
  console.log(countries);
  const [keyword, setKeyword] = useState(" ");

  // const filteredCountries =
  //   countries.filter((country) =>
  //     country.name.common.toLowerCase().includes(keyword)
  //   ) ||
  //   country.region.toLowerCase().includes(keyword) ||
  //   country.subregion.toLowerCase().includes(keyword);

  const filteredCountries = countries.filter(
    (country) =>
      country.name.common.toLowerCase().includes(keyword) ||
      country.region.toLowerCase().includes(keyword)
      // country.subregion.toLowerCase().includes(keyword)
  );

  const onInputChange = (e) => {
    e.preventDefault();

    setKeyword(e.target.value.toLowerCase());
  };

  return (
    <>
      {/* <MeetupList meetups={props.meetups} /> */}

      {/* <div className={styles.pagecontainer}>
     <ToolBar />

      <div className={styles.main}>
        <h1>Next.js News App</h1>

        <h3>Your one stop shop for the latest news articles</h3>
      </div>
    </div> */}

      <Layout>
        <div className={styles.counts}>Found {countries.length} countries</div>
        <SearchInput
          placeholder="Filter by Name,Region or SubRegion"
          onChange={onInputChange}
        />
        <CountriesTable countries={filteredCountries} />
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://restcountries.com/v3.1/all");
  const countries = await res.json();

  return {
    props: {
      countries,
    },
  };
};

// export async function getStaticProps() {
//   //fetch data from an api
//   return {
//     props: {
//       meetups: DUMMY_MEETUPS,
//     },
//     revalidate: 10,
//   };
// }

// export async function getServerSideProps(context){
//   const req=context.req
//   const res=context.res
//   //fetch data from an api
//   return{
//     props:{
//       meetups:DUMMY_MEETUPS
//     }
//   }
// }

export default HomePage;
